### PR TITLE
Update kubernetes.md

### PR DESCRIPTION
**Pull request by axelperschmann**
fixed helm syntax

### CODE REVIEW

**Comment by axelperschmann** [comment]
The command `polyaxon admin deploy -f config.yml` does not work as well, I guess it uses the deprecated helm syntax internally?

**Comment by mouradmourafiq** [comment]
What help version are you using?

**Comment by axelperschmann** [comment]
> What help version are you using?

`helm version`

```version.BuildInfo{Version:"v3.0.0-rc.4", GitCommit:"c7b722b837d24aa9e390b207fca86e9ef1716592", GitTreeState:"clean", GoVersion:"go1.13.4"}```

**Comment by mouradmourafiq** [comment]
I see, Polyaxon does not support Helm v3 yet, I think that Helm v3 was released just yesterday: https://helm.sh/blog/helm-3-released/

**Pull request closed without merging**
